Repository kubernetes-sigs/agent-sandbox, pull requests merged in 2025-10, with the labels that each got.

#8 Adding SandboxTemplate and SandboxClaim CRDs
  codegen.go
  extensions/api/v1alpha1/groupversion_info.go
  extensions/api/v1alpha1/sandboxclaim_types.go
  extensions/api/v1alpha1/sandboxtemplate_types.go
  extensions/api/v1alpha1/zz_generated.deepcopy.go
  k8s/crds/extensions.agents.x-k8s.io_sandboxclaims.yaml
  k8s/crds/extensions.agents.x-k8s.io_sandboxtemplates.yaml
Labels: size/XXL, lgtm, cncf-cla: yes, approved

#65 ci: add placeholder entrypoints for lint and e2e
  dev/ci/presubmits/lint-go
  dev/ci/presubmits/test-e2e
Labels: size/M, lgtm, cncf-cla: yes, approved

#51 Add support for shutdownTime in sandbox.spec
  api/v1alpha1/sandbox_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/sandbox_controller.go
  k8s/crds/agents.x-k8s.io_sandboxes.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#37 Example: Composition of Sandbox and NW Policies using KRO
  examples/composing-sandbox-nw-policies/README.md
  examples/composing-sandbox-nw-policies/instance.yaml
  examples/composing-sandbox-nw-policies/rgd.yaml
Labels: size/L, lgtm, cncf-cla: yes, approved

#62 Add development guide
  docs/development.md
Labels: size/L, lgtm, cncf-cla: yes, approved

#71 nit: updatd urlPath for Kyverno policy
  examples/policy/cluster-policy/prevent-sandbox-binding.yaml
Labels: size/XS, lgtm, cncf-cla: yes, approved, needs-ok-to-test

#73 Use sandbox volume claim template instead of creating PVs manually
  examples/vscode-sandbox/vscode-sandbox.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#69 chore: do not rely on preserveUnknownFields in CRDs
  api/v1alpha1/sandbox_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/sandbox_controller.go
  k8s/crds/agents.x-k8s.io_sandboxes.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#80 test: add coverage for sandbox top level Reconcile
  controllers/sandbox_controller_test.go
Labels: size/L, lgtm, cncf-cla: yes, approved

#82 feat: Implement .spec.replicas and /scale
  api/v1alpha1/sandbox_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/sandbox_controller.go
  controllers/sandbox_controller_test.go
  go.mod
  go.sum
  k8s/crds/agents.x-k8s.io_sandboxes.yaml
  test/e2e/basic_test.go
Labels: lgtm, cncf-cla: yes, size/XL, approved
