Repository kubernetes-sigs/agent-sandbox, pull requests merged in 2025-09, with the labels that each got.

#10 chore: add tools to apply correct headers
  .gitignore
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/sandbox_types.go
  cmd/main.go
  codegen.go
  controllers/sandbox_controller.go
  dev/tools/fix-boilerplate
  dev/tools/shared/headers.py
Labels: size/L, lgtm, cncf-cla: yes, approved

#15 chore: remove duplicate header scripts
  .nwa-config.yaml
  Makefile
  codegen.go
Labels: size/XS, lgtm, cncf-cla: yes, approved

#25 chore: add tool to fix gofmt
  dev/tools/fix-go-format
  dev/tools/shared/golang.py
  dev/tools/update-go-dependency
Labels: size/M, lgtm, cncf-cla: yes, approved

#11 chore: add presubmit script to verify fix-* scripts have been run
  dev/ci/presubmits/test-autogen-up-to-date
Labels: size/M, lgtm, cncf-cla: yes, approved

#28 remove manifests folder and add k8s folder
  k8s/crds/agents.x-k8s.io_sandboxes.yaml
Labels: size/L, lgtm, cncf-cla: yes, approved

#27 rename sandbox .spec.template -> .spec.podTemplate
  api/v1alpha1/sandbox_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/sandbox_controller.go
  examples/sandbox.yaml
  k8s/crds/agents.x-k8s.io_sandboxes.yaml
Labels: lgtm, cncf-cla: yes, approved, size/S

#49 Add kind deployment in makefile
  Makefile
  dev/tools/deploy-to-kube
  dev/tools/push-images
  dev/tools/shared/utils.py
Labels: size/M, lgtm, cncf-cla: yes, approved

#45 Example: Run vscode and gemini in a sandbox
  dev/tools/install-kro
  examples/vscode-sandbox/README.md
  examples/vscode-sandbox/devcontainer.json
  examples/vscode-sandbox/vscode-sandbox.yaml
Labels: size/L, lgtm, cncf-cla: yes, approved

#55 Add policy for token automount instead of mutating in the controller
  controllers/sandbox_controller.go
  examples/policy/sandbox-automount-token-binding.yaml
  examples/policy/sandbox-automount-token-policy.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved
